Lab2
izen57/PPO pull request #2
Opened 2022-05-13 12:55 UTC by izen57

Думаю, что первый пункт про описание стэка всё ещё не до конца закончил. Когда делал второй пункт, не нашёл схему, как работают Формы, поэтому сделал, как сам планирую) В третьем транспортные сущности пока такие же, как и системные...

2022-05-13 14:56 UTC, Sych474 requested changes

2022-05-13 14:56 UTC, Sych474 commented on README.md
> +Desktop-приложение на C#. Графический интерфейс реализован через Windows Forms.
Почему не WPF? Он хоть и тоже почти метрв, но не так сильно как вин-формы.

2022-05-13 14:56 UTC, Sych474 commented on README.md
> +## UML-схема "модельных" классов
В этой схеме у модельных сущностей есть метод Create что это за метод и для чего он используется?

2022-05-13 15:18 UTC, izen57 commented on README.md
> +Desktop-приложение на C#. Графический интерфейс реализован через Windows Forms.
Да, Вы правы. Почему-то думал, что кроме Windows Forms в C# ничего такого нету. Даже не проверил, получается.

2022-05-13 15:18 UTC, izen57 commented on README.md
> +## UML-схема "модельных" классов
Отвечает за создание соотв. класса?

2022-05-13 16:27 UTC, izen57 commented on README.md
> +## UML-схема "модельных" классов
исправил

2022-05-18 17:41 UTC, Sych474 approved these changes

2022-05-18 17:41 UTC, merged