Lab3
izen57/PPO pull request #3
Opened 2022-06-01 16:29 UTC by izen57

![изображение](https://user-images.githubusercontent.com/82231548/171454077-ca57a23c-f70f-4e19-aa05-e6c4e0cd94c9.png)

2022-06-01 22:20 UTC, Sych474 requested changes

2022-06-01 22:20 UTC, Sych474 commented on Database/AlarmClockRepo.cs
> +//}
Не стоит заливать в репозиторий закомменченные файлы

2022-06-01 22:20 UTC, Sych474 commented on Logic/StopwatchService.cs
> +			// start watch
?

2022-06-01 22:20 UTC, Sych474 commented on Logic/StopwatchService.cs
> +	internal class StopwatchService {
Сервис выглядит недописанным.

2022-06-01 22:20 UTC, Sych474 commented on Model/Note.cs
> +		public Guid Id { get; private set; }
Тут у вас приватные сеттеры, а в других мделях - нет, в чем причина?

2022-06-01 22:20 UTC, Sych474 commented on Logic/NotesService.cs
> +			//Note note = new(Guid.NewGuid(), body, isTemporal);
Для чего оставлены комментарии?

2022-06-01 22:20 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +			alarmClock.IsWorking = !alarmClock.IsWorking;
Почему тут нет сохранения в БД? Оно не нужно?

2022-06-19 14:10 UTC, Sych474 requested changes

2022-06-19 14:10 UTC, Sych474 commented on Model/Stopwatch.cs
> +		public List<TimeOnly> TimeFlags { get; set; }
Почему именно TimeOnly? Как будете действовать в случае если секундомен запустили день назад?

2022-06-19 14:10 UTC, Sych474 commented on Model/Note.cs
> +		public Guid Id { get; private set; }
Так в чем причина?

2022-06-19 14:10 UTC, Sych474 commented on Logic/StopwatchService.cs
> +			_stopwatch.IsWorking = !_stopwatch.IsWorking;
Почему-бы не держать структуру консестентной всегда? Сейчас вы позволяете при помощи ваших методов привести ее в невалидное состояние, вызвав Reset, и не вызвав ResetWork

2022-06-19 14:10 UTC, Sych474 commented on Logic/StopwatchService.cs
> +		public void Edit(string name, Color stopwatchColor, System.Diagnostics.Stopwatch timing, List<TimeOnly> timeFlags, bool isWorking) {
Прокидывать снаружи isWorking - не лучшая идея, особенно вместе со всем остальным и без каких-либо проверок на корректность изменения состояния таймера. 

Сейчас у вас легко можно передать запущенный timing и флаг, то он не включен. 

Для включения/выключения стоит сделать отдельные методы либо в самом стопвотче, либо в вашем сервисе

2022-06-19 14:10 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +			_repository.GetAllFiles("*");
Таким образом вы показываете отсутствие фильтра? 

Кажется не лучшее решение - делать самописный парсер фильтров...

2022-06-19 15:52 UTC, izen57 commented on Model/Note.cs
> +		public Guid Id { get; private set; }
Тут я думаю, что идентификатор можно давать заметке только изнутри. То есть, пользователю нет необходимости менять ID, тем более я его не планирую выводить в представление.

2022-07-01 13:46 UTC, Sych474 requested changes

2022-07-01 13:46 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +			_repository.GetAllFiles(pattern);
Имя метода тут меня смущает. А если реализация не на файлах будет?

2022-07-01 13:46 UTC, Sych474 commented on Logic/NotesService.cs
> +			_repository = repo ?? throw new ArgumentNullException(nameof(repo));
Тут есть проверка, а в куче других мест нет(

2022-07-01 13:46 UTC, Sych474 commented on TestPPO/UnitTest1.cs
> +namespace TestPPO {
Ну нейминг файлов (`UnitTest1`) прям из 1 семестра первого курса, не надо так...

2022-09-05 20:06 UTC, Sych474 requested changes

2022-09-05 20:06 UTC, Sych474 commented on Database/IAlarmClockRepo.cs
> +		List<string> GetAllAlarmClocks(string pattern);
pattern - это фильтр? Какой формат имеет? Как будет использоваться? Есть какие-то недопустимые паттерны и что будет возвращаться в этом случае?

Почему getAllAlarmClocks возвращает список строк?

2022-09-05 20:06 UTC, Sych474 commented on Database/INotesRepo.cs
> +		void Create(Note note);
Как вы узнаете какой Id у созданной сущности?

2022-09-05 20:06 UTC, Sych474 commented on Database/INotesRepo.cs
> +		List<string> GetAllNotes(string pattern);
Аналогичные вопросы про возвращаемый тип и параметр (как выше)

2022-09-05 20:06 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +			return alarmClock;
В этой сущности нет записанного Id, не уверен что имеет смысл ее возвращать...

2022-09-05 20:06 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +		public void List(string pattern) {
А зачем нужен этот метод, он же ничего не возвращает... И никаких побочных эффектов в нем нет.

2022-09-05 20:06 UTC, Sych474 commented on Logic/AlarmClockService.cs
> +			AlarmClock invertedAlarmClock = new(
В чем заключается Invert? Пока вижу что он просто копирует старый alarmClock

2022-09-05 20:06 UTC, Sych474 commented on Logic/NotesService.cs
> +			_repository.GetAllNotes("*");
В чем смысл этого метода?

2022-09-05 20:06 UTC, Sych474 commented on Logic/StopwatchService.cs
> +	public class StopwatchService {
У сервиса нет интерфейса, стоит добавить всем сервисам.

2022-09-06 18:56 UTC, izen57 commented on Database/IAlarmClockRepo.cs
> +		List<string> GetAllAlarmClocks(string pattern);
Да, `pattern` - это строка-фильтр, в неё будет передаваться название будильников, подходящих под паттерн. Если таких не будет найдено, то поднимится исключение.

2022-09-06 19:03 UTC, izen57 commented on Database/INotesRepo.cs
> +		void Create(Note note);
Так же, как у меня в модульных тестах:
```cs
Note note = new(Guid.NewGuid(), "моя первая заметка", false);
var id = note.Id;
```

2022-09-06 19:24 UTC, izen57 commented on Logic/AlarmClockService.cs
> +			return alarmClock;
исправил на `void`

2022-09-06 19:25 UTC, izen57 commented on Logic/AlarmClockService.cs
> +		public void List(string pattern) {
Исправил возвращаемый тип на список из будильников (или из заметок)

2022-09-06 19:26 UTC, izen57 commented on Logic/AlarmClockService.cs
> +			AlarmClock invertedAlarmClock = new(
Метод нужен, чтобы остановить работу будильника. Внутри чуть поправил

2022-09-10 18:32 UTC, Sych474 approved these changes

2022-09-11 14:58 UTC, merged